-- Create "emprendimientos" table
CREATE TABLE "emprendimientos" ("id_emprendimiento" serial NOT NULL, "nombre" character varying(255) NOT NULL, "url" character varying(255) NULL, "rubro" character varying(100) NOT NULL, "descripcion" text NULL, "logo" character varying(255) NULL, "contacto" character varying(255) NULL, "activo" boolean NULL DEFAULT true, "created_at" timestamptz NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("id_emprendimiento"));
-- Create "publicaciones" table
CREATE TABLE "publicaciones" ("id_publicacion" serial NOT NULL, "id_emprendimiento" integer NOT NULL, "titulo" character varying(255) NOT NULL, "contenido" text NULL, "imagen_url" character varying(255) NULL, "tipo" character varying(50) NOT NULL, "precio" numeric(10,2) NULL, "created_at" timestamptz NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("id_publicacion"), CONSTRAINT "fk_publicaciones_emprendimientos" FOREIGN KEY ("id_emprendimiento") REFERENCES "emprendimientos" ("id_emprendimiento") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "publicaciones_tipo_check" CHECK ((tipo)::text = ANY ((ARRAY['producto'::character varying, 'promocion'::character varying, 'servicio'::character varying, 'otro'::character varying])::text[])));
-- Create "usuarios" table
CREATE TABLE "usuarios" ("id_usuario" serial NOT NULL, "nombre_completo" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "clave" character varying(255) NOT NULL, "rol" character varying(50) NOT NULL, "id_emprendimiento" integer NULL, "created_at" timestamptz NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("id_usuario"), CONSTRAINT "fk_usuario_emprendimiento" FOREIGN KEY ("id_emprendimiento") REFERENCES "emprendimientos" ("id_emprendimiento") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "usuarios_rol_check" CHECK ((rol)::text = ANY ((ARRAY['emprendedor'::character varying, 'cliente'::character varying, 'administrador'::character varying])::text[])));
-- Create index "usuarios_email_key" to table: "usuarios"
CREATE UNIQUE INDEX "usuarios_email_key" ON "usuarios" ("email");
-- Create "suscripciones" table
CREATE TABLE "suscripciones" ("id_suscripcion" serial NOT NULL, "id_usuario" integer NOT NULL, "id_emprendimiento" integer NOT NULL, "fecha_sub" timestamptz NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("id_suscripcion"), CONSTRAINT "fk_suscripciones_emprendimiento" FOREIGN KEY ("id_emprendimiento") REFERENCES "emprendimientos" ("id_emprendimiento") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "fk_suscripciones_usuario" FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "uq_usuario_emprendimiento" to table: "suscripciones"
CREATE UNIQUE INDEX "uq_usuario_emprendimiento" ON "suscripciones" ("id_usuario", "id_emprendimiento");
