// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: emprendimientos.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createEmprendimiento = `-- name: CreateEmprendimiento :one
INSERT INTO emprendimientos (nombre, url, rubro, descripcion, logo, contacto, activo)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id_emprendimiento, nombre, url, rubro, descripcion, logo, contacto, activo, created_at
`

type CreateEmprendimientoParams struct {
	Nombre      string         `json:"nombre"`
	Url         sql.NullString `json:"url"`
	Rubro       string         `json:"rubro"`
	Descripcion sql.NullString `json:"descripcion"`
	Logo        sql.NullString `json:"logo"`
	Contacto    sql.NullString `json:"contacto"`
	Activo      sql.NullBool   `json:"activo"`
}

func (q *Queries) CreateEmprendimiento(ctx context.Context, arg CreateEmprendimientoParams) (Emprendimiento, error) {
	row := q.db.QueryRowContext(ctx, createEmprendimiento,
		arg.Nombre,
		arg.Url,
		arg.Rubro,
		arg.Descripcion,
		arg.Logo,
		arg.Contacto,
		arg.Activo,
	)
	var i Emprendimiento
	err := row.Scan(
		&i.IDEmprendimiento,
		&i.Nombre,
		&i.Url,
		&i.Rubro,
		&i.Descripcion,
		&i.Logo,
		&i.Contacto,
		&i.Activo,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmprendimiento = `-- name: DeleteEmprendimiento :exec
DELETE FROM emprendimientos
WHERE id_emprendimiento = $1
`

func (q *Queries) DeleteEmprendimiento(ctx context.Context, idEmprendimiento int32) error {
	_, err := q.db.ExecContext(ctx, deleteEmprendimiento, idEmprendimiento)
	return err
}

const getEmprendimiento = `-- name: GetEmprendimiento :one
SELECT id_emprendimiento, nombre, url, rubro, descripcion, logo, contacto, activo, created_at
FROM emprendimientos
WHERE id_emprendimiento = $1
`

func (q *Queries) GetEmprendimiento(ctx context.Context, idEmprendimiento int32) (Emprendimiento, error) {
	row := q.db.QueryRowContext(ctx, getEmprendimiento, idEmprendimiento)
	var i Emprendimiento
	err := row.Scan(
		&i.IDEmprendimiento,
		&i.Nombre,
		&i.Url,
		&i.Rubro,
		&i.Descripcion,
		&i.Logo,
		&i.Contacto,
		&i.Activo,
		&i.CreatedAt,
	)
	return i, err
}

const listEmprendimientos = `-- name: ListEmprendimientos :many
SELECT id_emprendimiento, nombre, url, rubro, descripcion, logo, contacto, activo, created_at
FROM emprendimientos
ORDER BY nombre
`

func (q *Queries) ListEmprendimientos(ctx context.Context) ([]Emprendimiento, error) {
	rows, err := q.db.QueryContext(ctx, listEmprendimientos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Emprendimiento
	for rows.Next() {
		var i Emprendimiento
		if err := rows.Scan(
			&i.IDEmprendimiento,
			&i.Nombre,
			&i.Url,
			&i.Rubro,
			&i.Descripcion,
			&i.Logo,
			&i.Contacto,
			&i.Activo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmprendimiento = `-- name: UpdateEmprendimiento :exec
UPDATE emprendimientos
SET nombre = $2, url = $3, rubro = $4, descripcion = $5, logo = $6, contacto = $7, activo = $8
WHERE id_emprendimiento = $1
`

type UpdateEmprendimientoParams struct {
	IDEmprendimiento int32          `json:"id_emprendimiento"`
	Nombre           string         `json:"nombre"`
	Url              sql.NullString `json:"url"`
	Rubro            string         `json:"rubro"`
	Descripcion      sql.NullString `json:"descripcion"`
	Logo             sql.NullString `json:"logo"`
	Contacto         sql.NullString `json:"contacto"`
	Activo           sql.NullBool   `json:"activo"`
}

func (q *Queries) UpdateEmprendimiento(ctx context.Context, arg UpdateEmprendimientoParams) error {
	_, err := q.db.ExecContext(ctx, updateEmprendimiento,
		arg.IDEmprendimiento,
		arg.Nombre,
		arg.Url,
		arg.Rubro,
		arg.Descripcion,
		arg.Logo,
		arg.Contacto,
		arg.Activo,
	)
	return err
}
