// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Emprendimiento struct {
	IDEmprendimiento int32          `json:"id_emprendimiento"`
	Nombre           string         `json:"nombre"`
	Url              sql.NullString `json:"url"`
	Rubro            string         `json:"rubro"`
	Descripcion      sql.NullString `json:"descripcion"`
	Logo             sql.NullString `json:"logo"`
	Contacto         sql.NullString `json:"contacto"`
	Activo           sql.NullBool   `json:"activo"`
	CreatedAt        sql.NullTime   `json:"created_at"`
}

type Publicacione struct {
	IDPublicacion    int32          `json:"id_publicacion"`
	IDEmprendimiento int32          `json:"id_emprendimiento"`
	Titulo           string         `json:"titulo"`
	Contenido        sql.NullString `json:"contenido"`
	ImagenUrl        sql.NullString `json:"imagen_url"`
	Tipo             string         `json:"tipo"`
	Precio           sql.NullString `json:"precio"`
	CreatedAt        sql.NullTime   `json:"created_at"`
}

type Suscripcione struct {
	IDSuscripcion    int32        `json:"id_suscripcion"`
	IDUsuario        int32        `json:"id_usuario"`
	IDEmprendimiento int32        `json:"id_emprendimiento"`
	FechaSub         sql.NullTime `json:"fecha_sub"`
}

type Usuario struct {
	IDUsuario        int32         `json:"id_usuario"`
	NombreCompleto   string        `json:"nombre_completo"`
	Email            string        `json:"email"`
	Clave            string        `json:"clave"`
	Rol              string        `json:"rol"`
	IDEmprendimiento sql.NullInt32 `json:"id_emprendimiento"`
	CreatedAt        sql.NullTime  `json:"created_at"`
}
