// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: publicaciones.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createPublicacion = `-- name: CreatePublicacion :one
INSERT INTO publicaciones (id_emprendimiento, titulo, contenido, imagen_url, tipo, precio)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id_publicacion, id_emprendimiento, titulo, contenido, imagen_url, tipo, precio, created_at
`

type CreatePublicacionParams struct {
	IDEmprendimiento int32          `json:"id_emprendimiento"`
	Titulo           string         `json:"titulo"`
	Contenido        sql.NullString `json:"contenido"`
	ImagenUrl        sql.NullString `json:"imagen_url"`
	Tipo             string         `json:"tipo"`
	Precio           sql.NullString `json:"precio"`
}

func (q *Queries) CreatePublicacion(ctx context.Context, arg CreatePublicacionParams) (Publicacione, error) {
	row := q.db.QueryRowContext(ctx, createPublicacion,
		arg.IDEmprendimiento,
		arg.Titulo,
		arg.Contenido,
		arg.ImagenUrl,
		arg.Tipo,
		arg.Precio,
	)
	var i Publicacione
	err := row.Scan(
		&i.IDPublicacion,
		&i.IDEmprendimiento,
		&i.Titulo,
		&i.Contenido,
		&i.ImagenUrl,
		&i.Tipo,
		&i.Precio,
		&i.CreatedAt,
	)
	return i, err
}

const deletePublicacion = `-- name: DeletePublicacion :exec
DELETE FROM publicaciones
WHERE id_publicacion = $1
`

func (q *Queries) DeletePublicacion(ctx context.Context, idPublicacion int32) error {
	_, err := q.db.ExecContext(ctx, deletePublicacion, idPublicacion)
	return err
}

const getPublicacion = `-- name: GetPublicacion :one
SELECT id_publicacion, id_emprendimiento, titulo, contenido, imagen_url, tipo, precio, created_at
FROM publicaciones
WHERE id_publicacion = $1
`

func (q *Queries) GetPublicacion(ctx context.Context, idPublicacion int32) (Publicacione, error) {
	row := q.db.QueryRowContext(ctx, getPublicacion, idPublicacion)
	var i Publicacione
	err := row.Scan(
		&i.IDPublicacion,
		&i.IDEmprendimiento,
		&i.Titulo,
		&i.Contenido,
		&i.ImagenUrl,
		&i.Tipo,
		&i.Precio,
		&i.CreatedAt,
	)
	return i, err
}

const listPublicacionesByEmprendimiento = `-- name: ListPublicacionesByEmprendimiento :many
SELECT id_publicacion, id_emprendimiento, titulo, contenido, imagen_url, tipo, precio, created_at
FROM publicaciones
WHERE id_emprendimiento = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPublicacionesByEmprendimiento(ctx context.Context, idEmprendimiento int32) ([]Publicacione, error) {
	rows, err := q.db.QueryContext(ctx, listPublicacionesByEmprendimiento, idEmprendimiento)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Publicacione
	for rows.Next() {
		var i Publicacione
		if err := rows.Scan(
			&i.IDPublicacion,
			&i.IDEmprendimiento,
			&i.Titulo,
			&i.Contenido,
			&i.ImagenUrl,
			&i.Tipo,
			&i.Precio,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
