// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createEmprendimiento = `-- name: CreateEmprendimiento :one
INSERT INTO emprendimientos (nombre, url, rubro, descripcion, logo, contacto, activo)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id_emprendimiento, nombre, url, rubro, descripcion, logo, contacto, activo, created_at
`

type CreateEmprendimientoParams struct {
	Nombre      string         `json:"nombre"`
	Url         sql.NullString `json:"url"`
	Rubro       string         `json:"rubro"`
	Descripcion sql.NullString `json:"descripcion"`
	Logo        sql.NullString `json:"logo"`
	Contacto    sql.NullString `json:"contacto"`
	Activo      sql.NullBool   `json:"activo"`
}

func (q *Queries) CreateEmprendimiento(ctx context.Context, arg CreateEmprendimientoParams) (Emprendimiento, error) {
	row := q.db.QueryRowContext(ctx, createEmprendimiento,
		arg.Nombre,
		arg.Url,
		arg.Rubro,
		arg.Descripcion,
		arg.Logo,
		arg.Contacto,
		arg.Activo,
	)
	var i Emprendimiento
	err := row.Scan(
		&i.IDEmprendimiento,
		&i.Nombre,
		&i.Url,
		&i.Rubro,
		&i.Descripcion,
		&i.Logo,
		&i.Contacto,
		&i.Activo,
		&i.CreatedAt,
	)
	return i, err
}

const createPublicacion = `-- name: CreatePublicacion :one
INSERT INTO publicaciones (id_emprendimiento, titulo, contenido, imagen_url, tipo, precio)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id_publicacion, id_emprendimiento, titulo, contenido, imagen_url, tipo, precio, created_at
`

type CreatePublicacionParams struct {
	IDEmprendimiento int32          `json:"id_emprendimiento"`
	Titulo           string         `json:"titulo"`
	Contenido        sql.NullString `json:"contenido"`
	ImagenUrl        sql.NullString `json:"imagen_url"`
	Tipo             string         `json:"tipo"`
	Precio           sql.NullString `json:"precio"`
}

func (q *Queries) CreatePublicacion(ctx context.Context, arg CreatePublicacionParams) (Publicacione, error) {
	row := q.db.QueryRowContext(ctx, createPublicacion,
		arg.IDEmprendimiento,
		arg.Titulo,
		arg.Contenido,
		arg.ImagenUrl,
		arg.Tipo,
		arg.Precio,
	)
	var i Publicacione
	err := row.Scan(
		&i.IDPublicacion,
		&i.IDEmprendimiento,
		&i.Titulo,
		&i.Contenido,
		&i.ImagenUrl,
		&i.Tipo,
		&i.Precio,
		&i.CreatedAt,
	)
	return i, err
}

const createSuscripcion = `-- name: CreateSuscripcion :one
INSERT INTO suscripciones (id_usuario, id_emprendimiento)
VALUES ($1, $2)
RETURNING id_suscripcion, id_usuario, id_emprendimiento, fecha_sub
`

type CreateSuscripcionParams struct {
	IDUsuario        int32 `json:"id_usuario"`
	IDEmprendimiento int32 `json:"id_emprendimiento"`
}

func (q *Queries) CreateSuscripcion(ctx context.Context, arg CreateSuscripcionParams) (Suscripcione, error) {
	row := q.db.QueryRowContext(ctx, createSuscripcion, arg.IDUsuario, arg.IDEmprendimiento)
	var i Suscripcione
	err := row.Scan(
		&i.IDSuscripcion,
		&i.IDUsuario,
		&i.IDEmprendimiento,
		&i.FechaSub,
	)
	return i, err
}

const createUsuario = `-- name: CreateUsuario :one
INSERT INTO usuarios (nombre_completo, email, clave, rol, id_emprendimiento)
VALUES ($1, $2, $3, $4, $5)
RETURNING id_usuario, nombre_completo, email, clave, rol, id_emprendimiento, created_at
`

type CreateUsuarioParams struct {
	NombreCompleto   string        `json:"nombre_completo"`
	Email            string        `json:"email"`
	Clave            string        `json:"clave"`
	Rol              string        `json:"rol"`
	IDEmprendimiento sql.NullInt32 `json:"id_emprendimiento"`
}

func (q *Queries) CreateUsuario(ctx context.Context, arg CreateUsuarioParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, createUsuario,
		arg.NombreCompleto,
		arg.Email,
		arg.Clave,
		arg.Rol,
		arg.IDEmprendimiento,
	)
	var i Usuario
	err := row.Scan(
		&i.IDUsuario,
		&i.NombreCompleto,
		&i.Email,
		&i.Clave,
		&i.Rol,
		&i.IDEmprendimiento,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmprendimiento = `-- name: DeleteEmprendimiento :exec
DELETE FROM emprendimientos
WHERE id_emprendimiento = $1
`

func (q *Queries) DeleteEmprendimiento(ctx context.Context, idEmprendimiento int32) error {
	_, err := q.db.ExecContext(ctx, deleteEmprendimiento, idEmprendimiento)
	return err
}

const deletePublicacion = `-- name: DeletePublicacion :exec
DELETE FROM publicaciones
WHERE id_publicacion = $1
`

func (q *Queries) DeletePublicacion(ctx context.Context, idPublicacion int32) error {
	_, err := q.db.ExecContext(ctx, deletePublicacion, idPublicacion)
	return err
}

const deleteSuscripcion = `-- name: DeleteSuscripcion :exec
DELETE FROM suscripciones
WHERE id_usuario = $1 AND id_emprendimiento = $2
`

type DeleteSuscripcionParams struct {
	IDUsuario        int32 `json:"id_usuario"`
	IDEmprendimiento int32 `json:"id_emprendimiento"`
}

func (q *Queries) DeleteSuscripcion(ctx context.Context, arg DeleteSuscripcionParams) error {
	_, err := q.db.ExecContext(ctx, deleteSuscripcion, arg.IDUsuario, arg.IDEmprendimiento)
	return err
}

const deleteUsuario = `-- name: DeleteUsuario :exec
DELETE FROM usuarios
WHERE id_usuario = $1
`

func (q *Queries) DeleteUsuario(ctx context.Context, idUsuario int32) error {
	_, err := q.db.ExecContext(ctx, deleteUsuario, idUsuario)
	return err
}

const getEmprendimiento = `-- name: GetEmprendimiento :one
SELECT id_emprendimiento, nombre, url, rubro, descripcion, logo, contacto, activo, created_at
FROM emprendimientos
WHERE id_emprendimiento = $1
`

func (q *Queries) GetEmprendimiento(ctx context.Context, idEmprendimiento int32) (Emprendimiento, error) {
	row := q.db.QueryRowContext(ctx, getEmprendimiento, idEmprendimiento)
	var i Emprendimiento
	err := row.Scan(
		&i.IDEmprendimiento,
		&i.Nombre,
		&i.Url,
		&i.Rubro,
		&i.Descripcion,
		&i.Logo,
		&i.Contacto,
		&i.Activo,
		&i.CreatedAt,
	)
	return i, err
}

const getPublicacion = `-- name: GetPublicacion :one
SELECT id_publicacion, id_emprendimiento, titulo, contenido, imagen_url, tipo, precio, created_at
FROM publicaciones
WHERE id_publicacion = $1
`

func (q *Queries) GetPublicacion(ctx context.Context, idPublicacion int32) (Publicacione, error) {
	row := q.db.QueryRowContext(ctx, getPublicacion, idPublicacion)
	var i Publicacione
	err := row.Scan(
		&i.IDPublicacion,
		&i.IDEmprendimiento,
		&i.Titulo,
		&i.Contenido,
		&i.ImagenUrl,
		&i.Tipo,
		&i.Precio,
		&i.CreatedAt,
	)
	return i, err
}

const getUsuario = `-- name: GetUsuario :one
SELECT id_usuario, nombre_completo, email, clave, rol, id_emprendimiento, created_at
FROM usuarios
WHERE id_usuario = $1
`

func (q *Queries) GetUsuario(ctx context.Context, idUsuario int32) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUsuario, idUsuario)
	var i Usuario
	err := row.Scan(
		&i.IDUsuario,
		&i.NombreCompleto,
		&i.Email,
		&i.Clave,
		&i.Rol,
		&i.IDEmprendimiento,
		&i.CreatedAt,
	)
	return i, err
}

const listEmprendimientos = `-- name: ListEmprendimientos :many
SELECT id_emprendimiento, nombre, url, rubro, descripcion, logo, contacto, activo, created_at
FROM emprendimientos
ORDER BY nombre
`

func (q *Queries) ListEmprendimientos(ctx context.Context) ([]Emprendimiento, error) {
	rows, err := q.db.QueryContext(ctx, listEmprendimientos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Emprendimiento
	for rows.Next() {
		var i Emprendimiento
		if err := rows.Scan(
			&i.IDEmprendimiento,
			&i.Nombre,
			&i.Url,
			&i.Rubro,
			&i.Descripcion,
			&i.Logo,
			&i.Contacto,
			&i.Activo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicacionesByEmprendimiento = `-- name: ListPublicacionesByEmprendimiento :many
SELECT id_publicacion, id_emprendimiento, titulo, contenido, imagen_url, tipo, precio, created_at
FROM publicaciones
WHERE id_emprendimiento = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPublicacionesByEmprendimiento(ctx context.Context, idEmprendimiento int32) ([]Publicacione, error) {
	rows, err := q.db.QueryContext(ctx, listPublicacionesByEmprendimiento, idEmprendimiento)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Publicacione
	for rows.Next() {
		var i Publicacione
		if err := rows.Scan(
			&i.IDPublicacion,
			&i.IDEmprendimiento,
			&i.Titulo,
			&i.Contenido,
			&i.ImagenUrl,
			&i.Tipo,
			&i.Precio,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuscripcionesByUsuario = `-- name: ListSuscripcionesByUsuario :many
SELECT id_suscripcion, id_usuario, id_emprendimiento, fecha_sub
FROM suscripciones
WHERE id_usuario = $1
`

func (q *Queries) ListSuscripcionesByUsuario(ctx context.Context, idUsuario int32) ([]Suscripcione, error) {
	rows, err := q.db.QueryContext(ctx, listSuscripcionesByUsuario, idUsuario)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Suscripcione
	for rows.Next() {
		var i Suscripcione
		if err := rows.Scan(
			&i.IDSuscripcion,
			&i.IDUsuario,
			&i.IDEmprendimiento,
			&i.FechaSub,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsuarios = `-- name: ListUsuarios :many
SELECT id_usuario, nombre_completo, email, clave, rol, id_emprendimiento, created_at
FROM usuarios
`

func (q *Queries) ListUsuarios(ctx context.Context) ([]Usuario, error) {
	rows, err := q.db.QueryContext(ctx, listUsuarios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(
			&i.IDUsuario,
			&i.NombreCompleto,
			&i.Email,
			&i.Clave,
			&i.Rol,
			&i.IDEmprendimiento,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmprendimiento = `-- name: UpdateEmprendimiento :exec
UPDATE emprendimientos
SET nombre = $2, url = $3, rubro = $4, descripcion = $5, logo = $6, contacto = $7, activo = $8
WHERE id_emprendimiento = $1
`

type UpdateEmprendimientoParams struct {
	IDEmprendimiento int32          `json:"id_emprendimiento"`
	Nombre           string         `json:"nombre"`
	Url              sql.NullString `json:"url"`
	Rubro            string         `json:"rubro"`
	Descripcion      sql.NullString `json:"descripcion"`
	Logo             sql.NullString `json:"logo"`
	Contacto         sql.NullString `json:"contacto"`
	Activo           sql.NullBool   `json:"activo"`
}

func (q *Queries) UpdateEmprendimiento(ctx context.Context, arg UpdateEmprendimientoParams) error {
	_, err := q.db.ExecContext(ctx, updateEmprendimiento,
		arg.IDEmprendimiento,
		arg.Nombre,
		arg.Url,
		arg.Rubro,
		arg.Descripcion,
		arg.Logo,
		arg.Contacto,
		arg.Activo,
	)
	return err
}

const updateUsuario = `-- name: UpdateUsuario :exec
UPDATE usuarios
SET nombre_completo = $2, email = $3, clave = $4, rol = $5, id_emprendimiento = $6
WHERE id_usuario = $1
`

type UpdateUsuarioParams struct {
	IDUsuario        int32         `json:"id_usuario"`
	NombreCompleto   string        `json:"nombre_completo"`
	Email            string        `json:"email"`
	Clave            string        `json:"clave"`
	Rol              string        `json:"rol"`
	IDEmprendimiento sql.NullInt32 `json:"id_emprendimiento"`
}

func (q *Queries) UpdateUsuario(ctx context.Context, arg UpdateUsuarioParams) error {
	_, err := q.db.ExecContext(ctx, updateUsuario,
		arg.IDUsuario,
		arg.NombreCompleto,
		arg.Email,
		arg.Clave,
		arg.Rol,
		arg.IDEmprendimiento,
	)
	return err
}
