// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: suscripciones.sql

package sqlc

import (
	"context"
)

const createSuscripcion = `-- name: CreateSuscripcion :one
INSERT INTO suscripciones (id_usuario, id_emprendimiento)
VALUES ($1, $2)
RETURNING id_suscripcion, id_usuario, id_emprendimiento, fecha_sub
`

type CreateSuscripcionParams struct {
	IDUsuario        int32 `json:"id_usuario"`
	IDEmprendimiento int32 `json:"id_emprendimiento"`
}

func (q *Queries) CreateSuscripcion(ctx context.Context, arg CreateSuscripcionParams) (Suscripcione, error) {
	row := q.db.QueryRowContext(ctx, createSuscripcion, arg.IDUsuario, arg.IDEmprendimiento)
	var i Suscripcione
	err := row.Scan(
		&i.IDSuscripcion,
		&i.IDUsuario,
		&i.IDEmprendimiento,
		&i.FechaSub,
	)
	return i, err
}

const deleteSuscripcion = `-- name: DeleteSuscripcion :exec
DELETE FROM suscripciones
WHERE id_usuario = $1 AND id_emprendimiento = $2
`

type DeleteSuscripcionParams struct {
	IDUsuario        int32 `json:"id_usuario"`
	IDEmprendimiento int32 `json:"id_emprendimiento"`
}

func (q *Queries) DeleteSuscripcion(ctx context.Context, arg DeleteSuscripcionParams) error {
	_, err := q.db.ExecContext(ctx, deleteSuscripcion, arg.IDUsuario, arg.IDEmprendimiento)
	return err
}

const listSuscripcionesByUsuario = `-- name: ListSuscripcionesByUsuario :many
SELECT id_suscripcion, id_usuario, id_emprendimiento, fecha_sub
FROM suscripciones
WHERE id_usuario = $1
`

func (q *Queries) ListSuscripcionesByUsuario(ctx context.Context, idUsuario int32) ([]Suscripcione, error) {
	rows, err := q.db.QueryContext(ctx, listSuscripcionesByUsuario, idUsuario)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Suscripcione
	for rows.Next() {
		var i Suscripcione
		if err := rows.Scan(
			&i.IDSuscripcion,
			&i.IDUsuario,
			&i.IDEmprendimiento,
			&i.FechaSub,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
