// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usuarios.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createUsuario = `-- name: CreateUsuario :one
INSERT INTO usuarios (nombre_completo, email, clave, rol, id_emprendimiento)
VALUES ($1, $2, $3, $4, $5)
RETURNING id_usuario, nombre_completo, email, clave, rol, id_emprendimiento, created_at
`

type CreateUsuarioParams struct {
	NombreCompleto   string        `json:"nombre_completo"`
	Email            string        `json:"email"`
	Clave            string        `json:"clave"`
	Rol              string        `json:"rol"`
	IDEmprendimiento sql.NullInt32 `json:"id_emprendimiento"`
}

func (q *Queries) CreateUsuario(ctx context.Context, arg CreateUsuarioParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, createUsuario,
		arg.NombreCompleto,
		arg.Email,
		arg.Clave,
		arg.Rol,
		arg.IDEmprendimiento,
	)
	var i Usuario
	err := row.Scan(
		&i.IDUsuario,
		&i.NombreCompleto,
		&i.Email,
		&i.Clave,
		&i.Rol,
		&i.IDEmprendimiento,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUsuario = `-- name: DeleteUsuario :exec
DELETE FROM usuarios
WHERE id_usuario = $1
`

func (q *Queries) DeleteUsuario(ctx context.Context, idUsuario int32) error {
	_, err := q.db.ExecContext(ctx, deleteUsuario, idUsuario)
	return err
}

const getUsuario = `-- name: GetUsuario :one
SELECT id_usuario, nombre_completo, email, clave, rol, id_emprendimiento, created_at
FROM usuarios
WHERE id_usuario = $1
`

func (q *Queries) GetUsuario(ctx context.Context, idUsuario int32) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUsuario, idUsuario)
	var i Usuario
	err := row.Scan(
		&i.IDUsuario,
		&i.NombreCompleto,
		&i.Email,
		&i.Clave,
		&i.Rol,
		&i.IDEmprendimiento,
		&i.CreatedAt,
	)
	return i, err
}

const listUsuarios = `-- name: ListUsuarios :many
SELECT id_usuario, nombre_completo, email, clave, rol, id_emprendimiento, created_at
FROM usuarios
`

func (q *Queries) ListUsuarios(ctx context.Context) ([]Usuario, error) {
	rows, err := q.db.QueryContext(ctx, listUsuarios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(
			&i.IDUsuario,
			&i.NombreCompleto,
			&i.Email,
			&i.Clave,
			&i.Rol,
			&i.IDEmprendimiento,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUsuario = `-- name: UpdateUsuario :exec
UPDATE usuarios
SET nombre_completo = $2, email = $3, clave = $4, rol = $5, id_emprendimiento = $6
WHERE id_usuario = $1
`

type UpdateUsuarioParams struct {
	IDUsuario        int32         `json:"id_usuario"`
	NombreCompleto   string        `json:"nombre_completo"`
	Email            string        `json:"email"`
	Clave            string        `json:"clave"`
	Rol              string        `json:"rol"`
	IDEmprendimiento sql.NullInt32 `json:"id_emprendimiento"`
}

func (q *Queries) UpdateUsuario(ctx context.Context, arg UpdateUsuarioParams) error {
	_, err := q.db.ExecContext(ctx, updateUsuario,
		arg.IDUsuario,
		arg.NombreCompleto,
		arg.Email,
		arg.Clave,
		arg.Rol,
		arg.IDEmprendimiento,
	)
	return err
}
